### PR TITLE
check for scaled position before calc fp

### PR DESCRIPTION
**Pull request by ray38**

### CODE REVIEW

**Comment by mshuaibii** [comment]
@ray38 looks like build failed. Tests don't pass this new test you put in place, but compute fingerprints just fine?

**Comment by ray38** [comment]
yes, I think we need to change the examples, and add system sizes to it so that we know for sure everything is working exactly like what we think it's doing. without setting the cell size, I actually think the fingerprints are not computed correctly. 
I'll soon submit another PR dealing with the PBC in the C part, but mainly just for performance optimization, shouldn't change the result

**Comment by mshuaibii** [comment]
> yes, I think we need to change the examples, and add system sizes to it so that we know for sure everything is working exactly like what we think it's doing. without setting the cell size, I actually think the fingerprints are not computed correctly.
> I'll soon submit another PR dealing with the PBC in the C part, but mainly just for performance optimization, shouldn't change the result

@ray38 I have now updated the tests.  Can you explain that system check...why must scaled positions be between 0 and 1? What combination of PBC/cell size causes this to fail?

**Comment by ray38** [comment]
I was going to share it on slack, but I guess it's a good idea to document it here as well.
the current work flow of computing  fps goes like following:
1. based on the size cell and cutoff range, divide the cell into equal sized bins (if cutoff > system size, only one bin per cell, if cell > cutoff, multiple bins per cell), and assign each atom to the bins based on the scaled position (this is why it's so important that scaled position is between [0, 1])
2. based on cutoff distance, loop though nearby cells. loop through each atom in each nearby cells to compute the fps

**Comment by ray38** [comment]
I actually don't know whether the fps were calculated correctly before, as the default cell size is very small, and the scaled position goes crazy. we could end up in a situation where we are essentially computing fps of several cells basically overlapped.

**Comment by mshuaibii** [comment]
> I actually don't know whether the fps were calculated correctly before, as the default cell size is very small, and the scaled position goes crazy. we could end up in a situation where we are essentially computing fps of several cells basically overlapped.

Interesting...good to know then. Are we fine to merge this then?

**Review by mshuaibii — APPROVED** [review]

**Pull request merged**
